import React from "react";
import ProgrammeDetail from "../../ProgrammeDetail";
import facultyData from "./facultyData/eceFacultyData";

export const programme = {
  id: "ece",
  name: "Electronics & Communication Engineering",
  short: "ECE",
  programmeType: "ug",
  programmeLabel: "B.E.",
  duration: "4 Years (8 Semesters)",
  intake: 120,
  studentsEnrolled: 4000,
  facultyStrength: 18,
  phdFaculty: 3,
  established: 2004,
  description: "The Department of Electronics & Communication Engineering (ECE), established in 2004, offers B.E. and M.Tech. programs and is a VTU-recognized research centre. With experienced faculty, modern laboratories, industry collaborations, and an Advanced Robotics Lab under IIT Bombay’s e-Yantra initiative, the department emphasizes project-based learning, research, and innovation. Students gain strong technical skills and secure placements in leading companies such as Infosys, Wipro, Cadence, and Sankalp Semiconductors.",
  image: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=1000&q=80",
  hodId: "f-nagaraj-bhat",
  facultyData,
  hideSharedClubs: true,
  labs: ["VLSI Lab", "Embedded Systems Lab", "Communication Lab", "DSP Lab"],
  research: "VLSI Design · Wireless Networks · IoT · Image Processing",
  accreditation: ["VTU Recognised Research Centre", "AICTE Approved"],
  // achievements: ["IEEE Best Student Branch Award (Karnataka Section), 2024", "Patent filed: Low-power VLSI architecture for IoT edge nodes", "Three students published in IEEE Sensors Journal, 2025"],
  projects: [
    { title: "5G Beamforming Test-bed", funding: "DST SERB", amount: "Rs. 18 L" },
    { title: "Wearable Health Monitor - Rural Karnataka", funding: "VGST", amount: "Rs. 9 L" },
  ],
  dashboard: [
    ["Faculty Members", "18"],
    ["Faculty with Ph.D.", "03"],
    ["Laboratories", "08"],
    ["Students Enrolled", "4000+"],
  ],
  academicOverview: [
    {
      title: "Academic Strengths",
      text: "The ECE Department is a VTU-recognized Research Centre with a strong academic foundation supported by 18 qualified faculty members, including Ph.D. holders with expertise in Communication Systems, VLSI Design, Embedded Systems, and Signal Processing. The department follows an NBA-aligned Outcome-Based Education framework that promotes research, innovation, and academic excellence.",
    },
    {
      title: "Practical Learning and Innovation",
      text: "The department provides extensive hands-on learning through modern laboratories equipped with advanced software and hardware tools, including Cadence, Xilinx, FPGA, Embedded Systems, and IoT platforms. Its Advanced Robotics Lab, established under IIT Bombay's e-Yantra initiative, encourages innovation, project development, internships, and research-driven learning.",
    },
    {
      title: "Interdisciplinary Learning Opportunities",
      text: "The department encourages interdisciplinary projects in electronics, communication, robotics, embedded systems, and emerging technologies. Through the Sanvahan student association, industry interactions, workshops, hackathons, and technical events, students gain practical exposure while developing teamwork, leadership, and problem-solving skills.",
    },
  ],
  curriculumSupport: [
    "VTU-approved curriculum aligned with NBA guidelines and Outcome-Based Education (OBE).",
    "Strong balance of theoretical learning, laboratory practice, and project work.",
    "Internship opportunities help students gain industry exposure in electronics, communication, embedded systems, and allied domains.",
    "Regular workshops and seminars keep students updated with IoT, VLSI, wireless communication, sensors, and emerging technologies.",
    "Value-added courses and certification programs enhance technical skills beyond the university curriculum.",
    // "Industry interactions bridge the gap between academic learning and industry requirements.",
    "Research and innovation opportunities through the VTU-recognized Research Centre.",
    "Continuous mentoring and academic guidance support students' overall growth and success.",
  ],
  programmeOutcomes: [
    "Engineering knowledge: Apply the knowledge of mathematics, science, engineering fundamentals, and an engineering specialization to the solution of complex engineering problems.",
    "Problem analysis: Identity, formulate, review research literature, and analyze complex engineering problems reaching substantiated conclusions using the first principles of mathematics, natural sciences, and engineering sciences",
    "Design/development of solutions: Design solutions for complex engineering problems and design system components or processes that meet the specified needs with appropriate consideration for public health and safety and cultural, societal, and environmental considerations.",
    "Conduct investigations of complex problems: Use research-based knowledge and research methods including design of experiments, analysis, interpretation of data, and synthesis of the information to provide valid conclusions.",
    "Modern tool usage: Create, select, and apply appropriate techniques, resources, and modern engineering and IT tools including prediction and modelling to complex engineering achieves with an understanding of the limitations.",
    "The engineer and society: Apply to reason informed by the contextual knowledge to assess societal, health, safety, legal and cultural issues and the consequent responsibilities relevant to the professional engineering practice.",
    "Environment and sustainability: Understand the impact of professional engineering solutions in societal and environmental contexts and demonstrate the knowledge of and need for sustainable development.",
    "Ethics: Apply ethical principles and commit to professional ethics and responsibilities and norms of the engineering practice.",
    "Individual and team work: Function effectively as an individual and as a member or leader in diverse teams and in multidisciplinary settings.",
    "Communication: Communicate effectively on complex engineering activities with the engineering community and with society at large, such as being able to comprehend and write effective reports and design documentation, make effective presentations and give and receive clear instructions.",
    "Project management and finance: Demonstrate knowledge and understanding of the engineering and management principles and apply these to one’s own work, as a member and leader in a team, to manage projects and in multidisciplinary environments",
    "Life-long learning: Recognize the need for, and have the preparation and ability to engage in independent and life-long learning in the broadest context of technological chang",
  ],
  pso: [
    "An ability to use appropriate modern techniques for analysis, design and development of VLSI and Embedded Systems",
    "Understand the architectural specifications of a communication system and determine their performance",
  ],
  peo: [
    "To be successful in professional career in electronics, communication and allied industries by acquiring the knowledge in the fundamentals of Electronics and Communication Engineering principles and professional skills",
    "To be in a position to analyze real life problems and design socially accepted and economically feasible solutions in the respective fields.",
    "To exhibit good communication skills in their professional career, lead a team with good leadership traits and good interpersonal relationship with the members related to other engineering streams.",
    "To involve themselves in lifelong learning and professional development by pursuing higher education and participation in research and development activities.",
    "To demonstrate professional and ethical responsibilities towards their profession, society and the environment.",
  ],
  // infrastructure: [
  //   ["Classrooms", "To be updated"],
  //   ["Laboratories", "4"],
  //   ["Computing Facilities", "To be updated"],
  //   ["Project Rooms", "To be updated"],
  //   ["Department Library", "To be updated"],
  //   ["Software Tools", "VLSI, embedded systems, communication, and signal processing tools"],
  //   ["Equipment Highlights", "Laboratories support practical learning in VLSI, embedded systems, communication systems, and DSP."],
  // ],
  studentActivities: {
    clubs: [
      {
        name: "ಸಂವಹನ (Sanvahan)",
        category: "Student Association",
        description: "ಸಂವಹನ (Sanvahan), the student association of the ECE Department, promotes technical excellence, innovation, leadership, and overall student development. It organizes workshops, expert talks, industry interactions, hackathons, project exhibitions, and technical events, helping students bridge the gap between academics and industry. Through active alumni engagement and student-led initiatives, Sanvahan fosters teamwork, professional growth, and lifelong learning.",
      },
    ],
    // professionalChapters: ["IEEE", "IETE", "IEI", "ISTE", "Technical workshops"],
  },
  
  facultyTable: [
    ["Dr. Nagaraj Bhat", "Ph.D. completed", "14 years"],
    ["Mrs. Rajeshwari Pashupatimath", "Pursuing Ph.D", "2years 5 months"],
    ["Mr. Raghavendra Nagaralli", "Pursuing Ph.D", "13 years"],
    ["Ms. Pavitra M Badiger", "Pursuing Ph.D", "2.5 years"],
    ["Mr. Sudheendra Yalagur", "Pursuing Ph.D", "15 years"],
    ["Mrs. Ashwini Garaddi", "Pursuing Ph.D", "2 years"],
    ["Mrs. Jyoti Kammar", "Pursuing Ph.D", "1 years"],
    ["Mr. Nikhil A. Kulkarni", "Pursuing Ph.D", "14 years"],
    ["Ms. Pooja C Shindhe", "Pursuing Ph.D", "4 years"],
    ["Mr. Suraj Kadli", "Pursuing Ph.D", "12 years"],
    ["Mr. A V Kolaki", "Pursuing Ph.D", "26 years"],
    ["Dr. Plasin Francis Dias", "Ph.D. completed", "26 years"],
    ["Mrs. Vijayalaxmi C. Kalal", "Pursuing Ph.D", "9 years"],
    ["Mrs. Rohini Kallur", "Pursuing Ph.D", "18 years"],
    ["Dr. Mahendra M. Dixit", "Ph.D. completed", "19 years"],
    ["Deepak Sharma", "Pursuing Ph.D", "11 years"],
  ],
  teachingStaff: [
    ["Dr. Nagaraj Bhat", "Associate Professor & HOD"],
    ["Mrs. Rajeshwari Pashupatimath", "Assistant Professor"],
    ["Mr. Raghavendra Nagaralli", "Assistant Professor"],
    ["Ms. Pavitra M Badiger", "Assistant Professor"],
    ["Mr. Sudheendra Yalagur", "Assistant Professor"],
    ["Mrs. Ashwini Garaddi", "Assistant Professor"],
    ["Mrs. Jyoti Kammar", "Assistant Professor"],
    ["Mr. Nikhil A. Kulkarni", "Assistant Professor"],
    ["Ms. Pooja C Shindhe", "Assistant Professor"],
    ["Mr. Suraj Kadli", "Assistant Professor"],
    ["Mr. A V Kolaki", "Assistant Professor"],
    ["Dr. Plasin Francis Dias", "Assistant Professor"],
    ["Mrs. Vijayalaxmi C. Kalal", "Assistant Professor"],
    ["Mrs. Rohini Kallur", "Assistant Professor"],
    ["Dr. Mahendra M. Dixit", "Professor & Dean"],
    ["Deepak Sharma", "Assistant Professor"],
  ],
  nonTeachingStaff: [],
};

const ECE = () => <ProgrammeDetail programme={programme} />;

export default ECE;